// Generated by scripts/gen-consensus.mjs. Do not edit by hand.
// EIP-712 values come from contracts/src/HaloVault.sol; the deployed address
// comes from consensus.json because a contract source cannot encode its own address.
export const VAULT_CHAIN_ID = 8453 as const;
export const VAULT_ADDRESS = "0x3907F660B257560883E891fbbB9F997Eff70E40E" as const;
export const EIP712_NAME = "Halo" as const;
export const EIP712_VERSION = "2" as const;
export const RESERVE_TYPE_STRING = "Reserve(address consumer,address operator,uint256 amount,uint64 expiry,uint256 nonce,uint256 keyEpoch)" as const;
export const RECEIPT_TYPE_STRING = "Receipt(address consumer,address operator,uint256 cumulative,uint256 keyEpoch,uint64 cycle)" as const;
export const RESERVE_TYPES = {
  "Reserve": [
    {
      "name": "consumer",
      "type": "address"
    },
    {
      "name": "operator",
      "type": "address"
    },
    {
      "name": "amount",
      "type": "uint256"
    },
    {
      "name": "expiry",
      "type": "uint64"
    },
    {
      "name": "nonce",
      "type": "uint256"
    },
    {
      "name": "keyEpoch",
      "type": "uint256"
    }
  ]
};
export const RECEIPT_TYPES = {
  "Receipt": [
    {
      "name": "consumer",
      "type": "address"
    },
    {
      "name": "operator",
      "type": "address"
    },
    {
      "name": "cumulative",
      "type": "uint256"
    },
    {
      "name": "keyEpoch",
      "type": "uint256"
    },
    {
      "name": "cycle",
      "type": "uint64"
    }
  ]
};
